NLT-79 카페 리스트 화면 추가
GyoSuIsChae/nyang-letter-client pull request #22
Opened 2023-02-06 14:50 UTC by chlee1001

## NLT-79 카페 리스트 화면 추가
- 리스트 뷰를 위해 `react-infinite-scroll-component` 라이브러리를 추가했습니다.
- 카페리스트 화면을 위해 임시 목업 데이터를 추가했습니다.
![image](https://user-images.githubusercontent.com/2025813/217003620-c114c512-78c9-4d6b-9a5a-6abfbe574691.png)

2023-02-07 01:15 UTC, uncoolclub requested changes

2023-02-07 01:15 UTC, uncoolclub commented on src/pages/Cafe/CafeList/index.tsx
> +      return COLORS.black001;
이거 `theme.colors.black001` 로 쓰는 게 맞을 것 같아요!

2023-02-07 01:20 UTC, chlee1001 commented on src/pages/Cafe/CafeList/index.tsx
> +      return COLORS.black001;
넵! 저런식으로 적어둔 것들 다 바꿔서 다시 올릴게여

2023-02-07 09:23 UTC, uncoolclub commented on src/pages/Cafe/CafeList/index.tsx
> +      return theme.colors.black001;
import 하는 거 말고

```jsx
return ${({ theme }) => theme.colors.black001}
```

요렇게 사용 못하나요?

2023-02-08 00:25 UTC, chlee1001 commented on src/pages/Cafe/CafeList/index.tsx
> +      return theme.colors.black001;
@uncoolclub 
그렇게 되는군요!!!
어떤방식으로 동작하는거에요??

2023-02-08 03:05 UTC, uncoolclub approved these changes
고생하셨습니다! ✨

2023-02-08 03:05 UTC, uncoolclub commented on src/components/CommonDatePicker/index.tsx
>  const ButtonText = styled(TX.Body1)<ButtonProps>`
```jsx
const ButtonText = styled(TX.Body1)<ButtonProps>`
  color: ${({ confirm, theme }) =>
    confirm
        ? theme.colors.white_grey001
        : theme.colors.black001
`;
```

2023-02-08 03:05 UTC, uncoolclub commented on src/components/CommonDatePicker/index.tsx
>  const ButtonText = styled(TX.Body1)<ButtonProps>`
이렇게 써 주는 게 더 깔끔할 것 같아요~

2023-02-08 05:00 UTC, merged